#!/bin/bash
echo "============================================================"
echo "🗑️  게시물 삭제 방법"
echo "============================================================"
echo ""
echo "방법 1: script 태그로 검색 (권장)"
echo "------------------------------------------------------------"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"DELETE FROM posts WHERE content LIKE '%<script%';\""
echo ""
echo "방법 2: 특정 ID 삭제"
echo "------------------------------------------------------------"
echo "# 먼저 ID 확인"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"SELECT id, user_id, LEFT(content, 50) as preview FROM posts ORDER BY id DESC LIMIT 5;\""
echo ""
echo "# ID로 삭제 (예: ID가 10인 경우)"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"DELETE FROM posts WHERE id = 10;\""
echo ""
echo "방법 3: 특정 날짜 이후 모든 게시물 삭제"
echo "------------------------------------------------------------"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"DELETE FROM posts WHERE created_at >= '2025-11-10 00:00:00';\""
echo ""
echo "방법 4: admin이 작성한 최근 게시물 삭제"
echo "------------------------------------------------------------"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"DELETE FROM posts WHERE user_id = 1 ORDER BY id DESC LIMIT 5;\""
echo ""
echo "방법 5: 모든 게시물 삭제 (주의!)"
echo "------------------------------------------------------------"
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"TRUNCATE TABLE posts;\""
echo ""
echo "============================================================"
