#!/bin/bash
echo "============================================================"
echo "📁 웹 루트 파일 구조 확인"
echo "============================================================"
echo ""
echo "리버스 쉘 또는 웹쉘에서 실행:"
echo ""
echo "# 1. 현재 디렉토리 확인"
echo "pwd"
echo ""
echo "# 2. /var/www/html 디렉토리 내용 확인"
echo "ls -la /var/www/html/"
echo ""
echo "# 3. index.php 파일 찾기"
echo "find /var/www/html -name 'index.php' -type f"
echo ""
echo "# 4. 모든 PHP 파일 확인"
echo "find /var/www/html -name '*.php' -type f"
echo ""
echo "# 5. www 디렉토리 확인 (있을 경우)"
echo "ls -la /var/www/html/www/"
echo ""
echo "============================================================"
