#!/bin/bash
echo "============================================================"
echo "💰 사용자 포인트 복구"
echo "============================================================"
echo ""
echo "리버스 쉘 또는 웹쉘에서 실행:"
echo ""
echo "mysql -u webuser -p'WebPassw0rd!' vulnerable_sns << 'SQL'"
echo "UPDATE users SET points = 1000000 WHERE username = 'admin';"
echo "UPDATE users SET points = 500 WHERE username = 'alice';"
echo "UPDATE users SET points = 300 WHERE username = 'bob';"
echo "SELECT username, points FROM users;"
echo "SQL"
echo ""
echo "============================================================"
