#!/bin/bash
echo "============================================================"
echo "🎯 auto.py CSRF 공격 테스트"
echo "============================================================"
echo ""
echo "1. 먼저 기존 게시물 삭제 (리버스 쉘에서):"
echo "   mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"DELETE FROM posts WHERE content LIKE '%🎁%';\""
echo ""
echo "2. Flask 서버 리셋:"
echo "   curl http://13.158.67.78:5000/reset"
echo ""
echo "3. alice 포인트 복구:"
echo "   mysql -u webuser -p'WebPassw0rd!' vulnerable_sns -e \"UPDATE users SET points = 500 WHERE username = 'alice';\""
echo ""
echo "4. auto.py 실행:"
echo "   python3 auto.py"
echo ""
echo "============================================================"
